// <auto-generated />
using System;
using ChurchTiming.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChurchTiming.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008200432_AddEnglishOfferingStartedAtSec")]
    partial class AddEnglishOfferingStartedAtSec
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ChurchTiming.Api.Data.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseOfferingSec")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EnglishOfferingStartedAtSec")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MasterStartAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreteachSec")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpanishSermonEndEtaSec")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpanishSermonEndedAtSec")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WalkBufferSec")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("ChurchTiming.Api.Data.RundownSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualSec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DriftSec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedSec")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("ChurchTiming.Api.Data.RundownSegment", b =>
                {
                    b.HasOne("ChurchTiming.Api.Data.Run", "Run")
                        .WithMany("Segments")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ChurchTiming.Api.Data.Run", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
